### ISSUE TITLE
Implement "Debug" Mode

### ISSUE THREAD

**Issue by Matthew-McRaven** [Matthew-McRaven/Pepp#396]
- [ ] At ASMB5, a full-height listing view of source code that can be flipped between User/OS (#388) 
- [x] At ISA3, it will will be a read-only object code editor (#393) -- eebb50f8cc55748d9a853cde69adcfbc269de9f6
- Remaining area used by
  - Vertical stack of:
    - [x] A CPU register view (#390) -- 279a56fe2423f658a0acb438d77ff9a6afd7828d
    - [x] Batch IO Pane (#391)
  - [x] Hex memory dump (#389) -- 5bbd20567dee359f0baaa73d01d0566e468b68aa
